POST http://localhost:3001/api/reports
Content-Type: application/json

{
  "consumptionSiteCode": "321-1232",
	"propertyCode": "53535-123",
	"meterSerialNumber": "4224-123",
	"address": "Testikatu 3",
	"postNumber": 20100,
	"postLocation": "Toijala",
	"reportType" : "Uusi pientuotanto",
	"isCompany": true,
	"ownerInfo": {
		"companyName": "Company Oy",
		"yTunnus": "1234567-8",
		"firstName": "John",
		"lastName": "Doe",
		"email": "john.doe@example.com",
		"phone": "123-456-7890" 
	},
	"hasContactPerson": true,
	"contactPerson": {
		"contactPersonFirstName": "Jack",
		"contactPersonLastName": "Bauer",
		"contactPersonEmail": "jack.bauer@example.com",
		"contactPersonPhone": "123-456-7890"
	},
	"contractor": {
		"contractorCompanyName": "Company Oy",
		"contractorTukesNumber": "15563-636",
		"contractorFirstName": "Steven",
		"contractorLastName": "Doe",
		"contractorEmail": "steven.doe@example.com",
		"contractorPhone": "123-456-7890"
	},
	"devices": [
		{
			"productionType": "AURINKOVOIMA",
			"powerProduction": 4,
			"inverterName": "Inverter 4",
			"inverterModel": "Model B",
			"inverterStructure": "HYBRIDI-INVERTTERI",
			"inverterACPower": 4,
			"hardwareConnection": "KOLMIVAIHEINEN", 
			"faultCurrent": 10,
			"shortCircuitCurrent": 20
		}
	],
	"productionTotal": 4,
  "currentProductionTotal": 4,
  "oldProductionTotal": 0,
  "productionDifference": 0, 
	"productionHardwareMeetsStandards": true,
	"locationHasIsolationSwitch": true,
	"isolationSwitchLocation": "Takaosassa, jossain siellä",
	"locationHasWarningSigns": true,
	"locationHasInterfaceProtection": true,
	"interfaceProtectionLocation": "Pitäis näkyä selvästi, mutta ei näy",
	"reactivePowerCompensation": true
}