POST http://localhost:3001/api/reports
Content-Type: application/json

    {
    "locationId": "123-1232",
    "propertyId": "21415-123",
    "meterSerialNumber": "151515-123",
    "address": "Katutie 6",
    "postNumber": 90100,
    "postLocation": "Oulu",
    "reportType" : "MUUTOSILMOITUS",
    "ownerInfo": {
      "companyName": "",
      "yTunnus": "",
      "firstName": "John",
      "lastName": "Doe",
      "email": "john.doe@example.com",
      "phone": "123-456-7890"
    },
    "contactPerson": {
      "firstName": "Jack",
      "lastName": "Bauer",
      "email": "jack.bauer@example.com",
      "phone": "123-456-7890"
    },
    "contractor": {
      "companyName": "Company Oy",
      "tukesNumber": "15563-636",
      "firstName": "Steven",
      "lastName": "Doe",
      "email": "steven.doe@example.com",
      "phone": "123-456-7890"
    },
    "devices": [
      {
        "productionType": "AURINKOVOIMA",
        "currentPowerProduction": 4,
        "inverterName": "Inverter 1",
        "inverterModel": "Model A",
        "inverterStructure": "HYBRIDI-INVERTTERI",
        "inverterACPower": 4,
        "hardwareConnection": "KOLMIVAIHEINEN",
        "faultCurrent": 10,
        "shortCircuitCurrent": 20
      },
      {
        "productionType": "DIESELVOIMA",
        "currentPowerProduction": 6,
        "inverterName": "Inverter 3",
        "inverterModel": "Model A",
        "inverterStructure": "ERILLISET INVERTTERIT",
        "inverterACPower": 6,
        "hardwareConnection": "L1",
        "faultCurrent": 10,
        "shortCircuitCurrent": 20
      },
      {
        "productionType": "ENERGIAVARASTO",
        "currentPowerProduction": 4,
        "inverterName": "Inverter 2",
        "inverterModel": "Model B",
        "inverterStructure": "ERILLISET INVERTTERIT",
        "inverterACPower": 4,
        "hardwareConnection": "L2",
        "faultCurrent": 10,
        "shortCircuitCurrent": 20
      }
    ],
    "currentPowerProductionTotal": 14,
    "productionDifferenceToLastSetup": 6,
    "productionHardwareMeetsStandards": true,
    "locationHasIsolationSwitch": true,
    "isolationSwitchLocation": "Takaosassa - punainen kytkin sulakekaapissa",
    "locationHasWarningSigns": true,
    "locationHasInterfaceProtection": true,
    "interfaceProtectionLocation": "Etuosassa - kytkinkaappi sinisellä suojanauhalla",
    "reactivePowerConpensation": true
  }