POST http://localhost:3001/api/reports
Content-Type: application/json

    {
    "consumptionSiteCode": "123-1232",
    "propertyCode": "21415-123",
    "meterSerialNumber": "151515-123",
    "address": "Rommakkokatu 2",
    "postNumber": 90100,
    "postLocation": "Oulu",
    "reportType" : "Muutosilmoitus",
    "isCompany": false,
    "ownerInfo": {
      "companyName": "",
      "yTunnus": "",
      "firstName": "Poppa",
      "lastName": "Maijanen",
      "email": "poppa.maijanen@example.com",
      "phone": "0504567890"
    },
    "hasContactPerson": true,
    "contactPerson": {
      "contactPersonFirstName": "Steve",
      "contactPersonLastName": "Austin",
      "contactPersonEmail": "steve.austin@wwe.com",
      "contactPersonPhone": "987655422"
    },
    "contractor": {
      "contractorCompanyName": "Asuntomarkkina Oy",
      "contractorTukesNumber": "15563-636",
      "contractorFirstName": "Remontti",
      "contractorLastName": "Reiska",
      "contractorEmail": "remontti.reiska@asuntomarkkinat.com",
      "contractorPhone": "1234567890"
    },
    "devices": [
      {
        "productionType": "AURINKOVOIMA",
        "powerProduction": 4,
        "inverterName": "Inverter 1",
        "inverterModel": "Model A",
        "inverterStructure": "HYBRIDI-INVERTTERI",
        "inverterACPower": 4,
        "hardwareConnection": "KOLMIVAIHEINEN",
        "faultCurrent": 10,
        "shortCircuitCurrent": 20
      },
      {
        "productionType": "DIESELVOIMA",
        "powerProduction": 6,
        "inverterName": "Inverter 3",
        "inverterModel": "Model A",
        "inverterStructure": "ERILLISET INVERTTERIT",
        "inverterACPower": 6,
        "hardwareConnection": "L1",
        "faultCurrent": 10,
        "shortCircuitCurrent": 20
      },
      {
        "productionType": "ENERGIAVARASTO",
        "powerProduction": 4,
        "inverterName": "Inverter 2",
        "inverterModel": "Model B",
        "inverterStructure": "ERILLISET INVERTTERIT",
        "inverterACPower": 4,
        "hardwareConnection": "L2",
        "faultCurrent": 10,
        "shortCircuitCurrent": 20
      }
    ],
    "productionTotal": 14,
    "currentProductionTotal": 14,
    "oldProductionTotal": 20,
    "productionDifference": 0, 
    "productionHardwareMeetsStandards": true,
    "locationHasIsolationSwitch": true,
    "isolationSwitchLocation": "Porstuan takaosassa - punainen kytkin sulakekaapissa",
    "locationHasWarningSigns": true,
    "locationHasInterfaceProtection": true,
    "interfaceProtectionLocation": "Porstuan etuosassa - kytkinkaappi sinisellä suojanauhalla",
    "reactivePowerCompensation": true
  }